
# set(req_COS_Intro COS_License)
set(req_COS_AndLogic COS_TrueFalse)
set(req_COS_OrLogic COS_TrueFalse)
set(req_COS_ListPre COS_Cons COS_TrueFalse)
set(req_COS_Map COS_ListPre)
set(req_COS_Series COS_Map COS_OrLogic COS_If COS_List)
set(req_COS_Translate COS_ListPre)
set(req_COS_List COS_ListPre COS_Translate COS_OrLogic)
set(req_COS_Complex COS_List COS_Map COS_Series)
set(req_COS_Dot COS_List)
set(req_COS_Element COS_List COS_Series COS_Hash COS_NewType)
set(req_COS_Let COS_List)
set(req_COS_MultipleParameter COS_Let)
set(req_COS_Implication COS_TrueFalse)
set(req_COS_Set COS_List COS_Implication)
set(req_COS_Graph COS_MultipleParameter)
set(req_COS_Begin COS_Let COS_Mutable)
set(req_COS_Hash COS_MultipleParameter)
set(req_COS_MutableStructure COS_List COS_Let COS_Map)
set(req_COS_Turing COS_MultipleParameter COS_Hash)
set(req_COS_Quote COS_List COS_Map)
set(req_COS_NewType COS_MultipleParameter COS_Set COS_Quote COS_Begin)
set(req_COS_Unless COS_TrueFalse COS_Hash COS_Begin COS_Map COS_Series)
set(req_COS_NOT COS_Unless)
set(req_COS_AND COS_Unless)
set(req_COS_OR COS_Unless)
set(req_COS_NOR COS_Unless)
set(req_COS_OSC COS_Unless)
set(req_COS_SR COS_Unless)
set(req_COS_D COS_Unless)
set(req_COS_UnlessProbe COS_NOT COS_AND)
set(req_COS_Message COS_Intro COS_List COS_Quote)
set(req_COS_JavaPrep COS_NewType COS_Series COS_Hash)
set(req_COS_JavaTest COS_JavaPrep)
set(req_COS_JavaValidate COS_JavaTest)
set(req_COS_Geo COS_NewType COS_Hash)
set(req_COS_JList_impl COS_JavaPrep)
set(req_COS_JList_test COS_JList_impl)
set(req_COS_JListIterator_impl COS_JList_impl)
set(req_COS_JDoor COS_JavaPrep)
set(req_COS_JThing COS_JavaPrep)
set(req_COS_JRoom COS_JavaPrep)
set(req_COS_JNamed COS_JavaPrep)
set(req_COS_JWorld COS_JavaPrep)
set(req_COS_JRobo COS_JavaPrep)
set(req_COS_JRoom_test COS_JRoom COS_JWorld COS_JDoor COS_JRobo COS_JThing COS_JNamed
  COS_JList_impl COS_JListIterator_impl)
