# In this file, we list the active chapters to be included in the default message,
# in order.

set(COSMIC_DEPENDS
  COS_License
  COS_Intro
  COS_Compare
  COS_NotLogic 
  COS_Unary
  COS_Addition
  COS_Subtraction
  COS_Multiplication
  COS_Binary
  COS_Evaluation
  COS_DefineFunction
  COS_TrueFalse
  COS_If
  COS_AndLogic
  COS_OrLogic
  COS_Cons
  COS_Mutable
  COS_ListPre
  COS_Map
  COS_Series
  COS_Translate
  COS_List
  COS_Let
  COS_MultipleParameter
  COS_CommentBase
  COS_Pure
  COS_Quantifier
  COS_Implication
  COS_Set
  COS_Graph
  COS_Begin
  COS_Hash
  COS_MutableStructure
  COS_Method
  COS_Turing
  COS_NewType
  COS_CommentBase2
  COS_Unless
  COS_NOT
  COS_AND
  COS_OR
  COS_NOR
  COS_OSC
  COS_SR
  COS_D
  COS_UnlessProbe
  COS_CommentBase3
  COS_Message
  COS_MARK
  COS_JavaPrep
  COS_JavaTest
  COS_JavaValidate
  COS_Geo
  COS_JList_impl
  COS_JList
  COS_JHashMap
  COS_JList_test
  COS_JListIterator_impl
  COS_JListIterator
  COS_JDoor
  COS_JThing
  COS_JRoom
  COS_JNamed
  COS_JWorld
  COS_JRobo
  COS_JRoom_test)

# touch 1
