separate_arguments(in)
file(WRITE ${out} "")
foreach(f ${in})
  file(APPEND ${out} "== ${f} ==\n")
  if (EXISTS ${f}_md.ftz)
    file(READ ${f}_md.ftz CONTENTS)
    file(APPEND ${out} "${CONTENTS}")
  endif()
  file(READ ${f}.ftz CONTENTS)
  file(APPEND ${out} "${CONTENTS}")
endforeach()
